# Set platform
platform :ios, '13.1'

# Define flutter_root method
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}"
end

# Import Flutter helpers
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

# CocoaPods settings
install! 'cocoapods', 
  :deterministic_uuids => false,
  :integrate_targets => true

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Install Flutter pods
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  # Add flutter_blue_plus pod explicitly

  
  # Your local framework
  pod 'QCBandSDK', :path => 'frameworks/QCBandSDK.framework'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # Add this block to set the preprocessor macro
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PERMISSION_MICROPHONE=1',
        'PERMISSION_SPEECH_RECOGNIZER=1'
      ]
    end
  end
end